/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.app.assets;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Kirin
 */
public class OrderPanel extends javax.swing.JPanel {
    
   ImageIcon originalIcon;
   ImageIcon scaledIcon;


    /**
     * Creates new form OrderPanel
     */
    public OrderPanel() {
        initComponents();
    }
    
    public void setOrderImage(String imagePath) {
        // Load the image from the specified path
        ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
        
        // Set the image for the PictureBox
        OrderImage.setIcon(icon);
    }
    
    public void setFoodName(String foodName) {
        FoodName.setText(foodName);
    }
    
    public void setFoodDescription(String foodDescription) {
        FoodDescription.setText(foodDescription);
    }
    
    public void setFoodPrice(String foodPrice) {
        FoodPrice.setText(foodPrice);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OrderPanelBG = new javax.swing.JPanel();
        OrderImage = new javax.swing.JLabel();
        OrderPanel = new javax.swing.JPanel();
        FoodPrice = new javax.swing.JLabel();
        QuantityLabel = new javax.swing.JLabel();
        FoodName = new javax.swing.JLabel();
        FoodDescription = new javax.swing.JLabel();
        MinusButton = new com.app.assets.ColoredButton();
        plusButton = new com.app.assets.ColoredButton();
        Quantity = new javax.swing.JLabel();
        CheckoutButton = new com.app.assets.ColoredButton();
        CartButton = new com.app.assets.ColoredButton();

        setPreferredSize(new java.awt.Dimension(410, 280));
        setRequestFocusEnabled(false);

        OrderPanelBG.setBackground(new java.awt.Color(241, 242, 237));
        OrderPanelBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrderImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrderImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/images/foodimage.png"))); // NOI18N
        OrderPanelBG.add(OrderImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 170, -1));

        OrderPanel.setBackground(new java.awt.Color(214, 212, 199));

        FoodPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FoodPrice.setText("PHP 100.00");

        QuantityLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        QuantityLabel.setText("Quantity");

        FoodName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FoodName.setText("Food Name");

        FoodDescription.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        FoodDescription.setText("Food Description");

        MinusButton.setText("-");
        MinusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusButtonActionPerformed(evt);
            }
        });

        plusButton.setText("+");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        Quantity.setBackground(new java.awt.Color(255, 255, 255));
        Quantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quantity.setText("1");
        Quantity.setOpaque(true);

        CheckoutButton.setText("CHECKOUT");

        CartButton.setText("CART");

        javax.swing.GroupLayout OrderPanelLayout = new javax.swing.GroupLayout(OrderPanel);
        OrderPanel.setLayout(OrderPanelLayout);
        OrderPanelLayout.setHorizontalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FoodDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FoodName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FoodPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(OrderPanelLayout.createSequentialGroup()
                        .addComponent(QuantityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderPanelLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(CartButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        OrderPanelLayout.setVerticalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(FoodName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FoodDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FoodPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityLabel)
                    .addComponent(MinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CartButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        OrderPanelBG.add(OrderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OrderPanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OrderPanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        int currentQuantity = Integer.parseInt(Quantity.getText());
        if (currentQuantity < 99) {
            // Increase quantity
            Quantity.setText(String.valueOf(currentQuantity + 1));
        }
    }//GEN-LAST:event_plusButtonActionPerformed

    private void MinusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusButtonActionPerformed
        int currentQuantity = Integer.parseInt(Quantity.getText());
        if (currentQuantity > 1) {
            // Decrease quantity
            Quantity.setText(String.valueOf(currentQuantity - 1));
        }
    }//GEN-LAST:event_MinusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.app.assets.ColoredButton CartButton;
    private com.app.assets.ColoredButton CheckoutButton;
    private javax.swing.JLabel FoodDescription;
    private javax.swing.JLabel FoodName;
    private javax.swing.JLabel FoodPrice;
    private com.app.assets.ColoredButton MinusButton;
    private javax.swing.JLabel OrderImage;
    private javax.swing.JPanel OrderPanel;
    private javax.swing.JPanel OrderPanelBG;
    private javax.swing.JLabel Quantity;
    private javax.swing.JLabel QuantityLabel;
    private com.app.assets.ColoredButton plusButton;
    // End of variables declaration//GEN-END:variables
}
