/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.main;

import com.app.sections.ProduceSection;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Kirin
 */
public class HomePage extends javax.swing.JFrame {
    
   
    public HomePage() {
        initComponents();
        
        
        
        
        //BackButtons
        
        ActionListener backButtonListener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            JButton sourceButton = (JButton) e.getSource();
            System.out.println("Button Works");
            ((HomePage) SwingUtilities.getWindowAncestor(sourceButton)).switchToCategorySection();
        }
     };

     ProduceBackButton.addActionListener(backButtonListener);
     BeverageBackButton.addActionListener(backButtonListener);
     SnackBackButton.addActionListener(backButtonListener);   
     MeatBackButton.addActionListener(backButtonListener);
     SeafoodBackButton.addActionListener(backButtonListener);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CategoryPage = new javax.swing.JPanel();
        CategorySection = new com.app.sections.CategorySection();
        ProducePage = new javax.swing.JPanel();
        ProduceBackButton = new assets.coloredbutton();
        ProduceSection = new com.app.sections.ProduceSection();
        BeveragePage = new javax.swing.JPanel();
        BeverageBackButton = new assets.coloredbutton();
        BeverageSection = new com.app.sections.BeverageSection();
        SnackPage = new javax.swing.JPanel();
        SnackBackButton = new assets.coloredbutton();
        SnackSection = new com.app.sections.SnackSection();
        MeatPage = new javax.swing.JPanel();
        MeatBackButton = new assets.coloredbutton();
        MeatSection = new com.app.sections.MeatSection();
        SeafoodPage = new javax.swing.JPanel();
        SeafoodBackButton = new assets.coloredbutton();
        SeafoodSection = new com.app.sections.SeafoodSection();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        CategoryPage.setPreferredSize(new java.awt.Dimension(1280, 720));

        javax.swing.GroupLayout CategoryPageLayout = new javax.swing.GroupLayout(CategoryPage);
        CategoryPage.setLayout(CategoryPageLayout);
        CategoryPageLayout.setHorizontalGroup(
            CategoryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryPageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CategorySection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CategoryPageLayout.setVerticalGroup(
            CategoryPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CategoryPageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CategorySection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(CategoryPage, "card2");

        ProducePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProduceBackButton.setText("<-");
        ProduceBackButton.setRadius(100);
        ProducePage.add(ProduceBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 50, 50));
        ProducePage.add(ProduceSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(ProducePage, "card3");

        BeveragePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BeverageBackButton.setText("<-");
        BeverageBackButton.setRadius(100);
        BeveragePage.add(BeverageBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 50, 50));
        BeveragePage.add(BeverageSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(BeveragePage, "card4");

        SnackPage.setPreferredSize(new java.awt.Dimension(1280, 720));
        SnackPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SnackBackButton.setText("<-");
        SnackBackButton.setRadius(100);
        SnackPage.add(SnackBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 50, 50));
        SnackPage.add(SnackSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(SnackPage, "card5");

        MeatPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MeatBackButton.setText("<-");
        MeatBackButton.setRadius(100);
        MeatPage.add(MeatBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 50, 50));
        MeatPage.add(MeatSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(MeatPage, "card6");

        SeafoodPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SeafoodBackButton.setText("<-");
        SeafoodBackButton.setRadius(100);
        SeafoodPage.add(SeafoodBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 50, 50));
        SeafoodPage.add(SeafoodSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(SeafoodPage, "card7");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }
    
    public void switchToProduceSection() {
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "card3");
    }
    
    public void switchToBeverageSection() {
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "card4");
    }
    
    public void switchToSnackSection() {
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "card5");
    }
    
    public void switchToMeatSection() {
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "card6");
    }
    
    public void switchToSeafoodSection() {
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "card7");
    }
    
    public void switchToCategorySection() {
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(getContentPane(), "card2");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assets.coloredbutton BeverageBackButton;
    private javax.swing.JPanel BeveragePage;
    private com.app.sections.BeverageSection BeverageSection;
    private javax.swing.JPanel CategoryPage;
    private com.app.sections.CategorySection CategorySection;
    private assets.coloredbutton MeatBackButton;
    private javax.swing.JPanel MeatPage;
    private com.app.sections.MeatSection MeatSection;
    private assets.coloredbutton ProduceBackButton;
    private javax.swing.JPanel ProducePage;
    private com.app.sections.ProduceSection ProduceSection;
    private assets.coloredbutton SeafoodBackButton;
    private javax.swing.JPanel SeafoodPage;
    private com.app.sections.SeafoodSection SeafoodSection;
    private assets.coloredbutton SnackBackButton;
    private javax.swing.JPanel SnackPage;
    private com.app.sections.SnackSection SnackSection;
    // End of variables declaration//GEN-END:variables
}
